/** 
 * Auto-generated by effect-start.
 */

import type { Router } from "effect-start"

const layout__ = {
  path: "/",
  load: () => import("./_layout.tsx"),
} as const

const page__ = {
  path: "/",
  parent: layout__,
  load: () => import("./_page.tsx"),
} as const

const page__about = {
  path: "/about",
  parent: layout__,
  load: () => import("./about/_page.tsx"),
} as const

const server___well_known__farcaster_json = {
  path: "/.well-known/farcaster.json",
  load: () => import("./.well-known/farcaster.json/_server.ts"),
} as const

const server__api__debug = {
  path: "/api/debug",
  load: () => import("./api/debug/_server.ts"),
} as const

const server__api__embed = {
  path: "/api/embed",
  load: () => import("./api/embed/_server.ts"),
} as const

const server__api__pnl = {
  path: "/api/pnl",
  load: () => import("./api/pnl/_server.ts"),
} as const

const server__api__portfolio = {
  path: "/api/portfolio",
  load: () => import("./api/portfolio/_server.ts"),
} as const

const server__api__positions = {
  path: "/api/positions",
  load: () => import("./api/positions/_server.ts"),
} as const

export const Layouts: Router.LayoutRoutes = [
  layout__
] as const

export const Pages: Router.PageRoutes = [
  page__,
  page__about
] as const

export const Servers: Router.ServerRoutes = [
  server___well_known__farcaster_json,
  server__api__debug,
  server__api__embed,
  server__api__pnl,
  server__api__portfolio,
  server__api__positions
] as const
 